### PR TITLE
Add Save All to file menu

### PR DESCRIPTION
**Pull request by sl0burn**
Saves all modified tabs in window with focus

### CODE REVIEW

**Comment by mscharley** [comment]
There's no tests, but other than that and my comments above about style, this seems fine on my end.

**Comment by kattrali** [comment]
Maybe we could move the implementation from `runnables` plugin, since it has an equivalent save for use before running a command:

https://github.com/redcar/redcar/blob/master/plugins/runnables/lib/runnables.rb#L26

``` ruby
window.notebooks.each do |notebook|
   notebook.tabs.each do |tab|
      tab.edit_view.document.save! if tab.is_a?(EditTab) and tab.edit_view.document.modified?
   end
end
```

?

**Comment by mscharley** [comment]
There's important points in both. `tab.is_a?(EditTab)` is one check that this patch doesn't have that's needed. Other than that, I do like the original implementation because it reuses the SaveCommand so if we need to change how commands save files for some reason it's only one piece of code. Honestly though, either's fine to me though.'

One question that comes to my mind is how does each of these approaches play with things like the REPL tabs and SCM commit messages?

**Comment by kattrali** [comment]
Probably doesn't play very well, I'd imagine. Is there a good way to check whether an object is an instance of EditTab and not a subclass?

**Comment by sl0burn** [comment]
Firstly , thanks for the feedback - I wanted to start small and learn the right way to do things.

I had originally done this in notepad++ which screwed up the tabs, Then tried to clean it up by re-editing in redcar.

I got most of the modified checking code from EditView::ModifiedTabsChecker. I had not run across the runnables code. In fact I have not been using runnables at all as I have been executing using the execute plugin.

I had originally tossed up reusing the ModifiedTabsChecker directly so as not to duplicate code. It seems like creating a function in one place to "return a list of modified edit tabs" would make sense - not sure where this should reside though.

I will add tests for it as suggested and fix the editing.
Will await your feedback about my refactoring suggestions.

**Pull request closed without merging**
