### PR TITLE
Use << instead of += for strings

### PR DESCRIPTION
**Pull request by stevenheidel**

### CODE REVIEW

**Comment by mscharley** [comment]
What is the point of this change? Seems to obfuscate the code more than help to me.

**Comment by stevenheidel** [comment]
## "string <<" is up to 71% faster over 1000 repetitions

```
string <<    0.00270986557006836 secs    Fastest
string +=        0.00948691368103027 secs    71% Slower
```

**Comment by mscharley** [comment]
Admittedly, I'm a newbie at ruby, but I've never seen << used for concatenation before... Looks weird, but it seems to chain properly so I can't really say no, except to flag that it looks strange and unusual.

**Comment by mscharley** [comment]
On a seperate note, feature branches would have kept this pull request a bit cleaner :)

**Comment by stevenheidel** [comment]
Sorry about that.

**Pull request merged**
