### PR TITLE
Use bundler to manage vendored dependencies.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
The rake init task was quite brittle, namely it didn't work
for me at all. Furthermore, it duplicates an awful lot of Bundler's
functionality. However we most likely _don't_ want Bundler to become a
runtime dependency and we still want access to the gem sources for
packaging purposes. For that reason the new init rake task uses bundler
in standalone (no bundler needed at runtime) and installs to the vendor
path.

This patch may also improve startup time ever so slightly by reducing the number of calls
to File.expand_path from 6 down to 3.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I still need to do work to ensure that packaging still works with the bundler formatted gem paths but I wanted to start the discussion around this patch to make sure it was welcome. It seems cleaner and easier to alter dependencies moving foward this way.

**Comment by kattrali** [comment]
I don't know enough about all of the issues surrounding how redcar was using bundler and then wasn't (at least, I can't find the info immediately in on the mailing list). I can at least fix the Rakefile in the meantime though.

Anyone else around to comment?

**Comment by DouglasAllen** [comment]
What version do I use to install as  dpkg -i redcar_xx_all.deb?

**Comment by kattrali** [comment]
Current version is 0.14dev, there are builds from a few weeks ago that can be downloaded here: https://github.com/redcar/redcar/downloads

**Pull request merged**
