### PR TITLE
ignored files in one storage not three

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by danlucraft** [comment]
Wow I didn't realize those comments would appear here. Pull requests are cool.

Anyway, this looks good. If you agree with the above suggestions you can make those changes and I'll merge it then. Thanks :)

**Comment by ghost** [comment]
I thought shared would be a nice name for a file all plugins could store shared data, so that where is only one shared configuration. May be object to discussion.

SharedStorage should only contain Arrays because i can't do a update_default methods that can merge Strings, Regexps, Hashes, Arrays, $custom_type_here. Merging arrays is simple, but all other types can't be merged really nice. If #update_default doesn't get an Array, it simply appends to the array already existing, so in the end we have an Array in both ways.

**Comment by ghost** [comment]
I have no experience with testing yet, but I'll try to do some tests that make sense :)

**Comment by danlucraft** [comment]
Merged it, thanks!

**Pull request merged**
